### ISSUE TITLE
Fuel pump button state not updated correctly

### ISSUE THREAD

**Issue by eranjo** [paulalexandrow/a32nx-webremote#10]
Ps. Any chance making multiple tabs for each instrument cluster? One tab for overhead one for center cluster and so on? Visually it would be also easier to find the buttons if the look and the feel would mimic what we see on the sim. Now I find it really hard to spot the correct cluster and action.

**Comment by paulalexandrow** [comment]
Which fuel pump are you referring to? Or is it the fuel valves? Can you confirm you updated the aircraft to version d415b60 or later and that you updated myOffsets.txt when you upgraded WebRemote?

About your PS: I am not sure I can follow your suggestion. What do you mean by "tabs"? Also, kindly open a separate issue with that request. If you could provide a quick doodle of your idea there, that would be great.

**Comment by paulalexandrow** [comment]
Can't reproduce.
