### ISSUE TITLE
Final step goes wrong

### ISSUE THREAD

**Issue by McSchulz** [paulalexandrow/a32nx-webremote#13]
Hi Paul, hope you are fine.

I followed your instructions to setup webremote.

I successfully can open webremote via index.html and my url: ws://192.xxx.xxx.xx:2048/fsuipc/
IIS is installed, server and setup of rule etc. is set up as you described.

On my iPad I can open the site 192.xxx.xxx.xx and get the logon of webremote suggesting ws://192.xxx.xxx.xx/fsuipc/, but get the error "A socket error occured."

Can you give me a hint what I did wrong?

Kind regards,

Mario (Germany)

**Comment by paulalexandrow** [comment]
It sounds like something is wrong with the configuration of the forward proxy. This could be related to any of the following steps of the configuration guide: 1 (second part), 2, 4, 9 or 10. Kindly check those again if there hasn't been something you accidentally missed.

If unsuccessful, please check the following, which will help me to narrow down the issue:
- Open `192.xxx.xxx.xx` on the **local** computer. Does the page load?
- On that page/browser, open a connection to `ws://192.xxx.xxx.xx/fsuipc/`. Does it work?
- On that page/browser, open a connection to `ws://localhost/fsuipc/`. Does it work?

Additionally a screenshot of the configuration of your "Inbound Rule" will help.

Also note, that old versions of iOS do not support WebSocket connections at all. I don't know what iOS your iPad is running, but if it is an older model you should try on a newer machine, perferably another PC or, if you do not have one, your phone maybe.

**Comment by McSchulz** [comment]
Hi Paul, thanks for your quick answer.

 

See my feedback down below:

 

Von: Paul Alexandrow ***@***.***> 
Gesendet: Montag, 4. Dezember 2023 12:37
An: paulalexandrow/a32nx-webremote ***@***.***>
Cc: McSchulz ***@***.***>; Author ***@***.***>
Betreff: Re: [paulalexandrow/a32nx-webremote] Final step goes wrong (Issue #13)

 

It sounds like something is wrong with the configuration of the forward proxy. This could be related to any of the following steps of the configuration guide: 1 (second part), 2, 4, 9 or 10. Kindly check those again if there hasn't been something you accidentally missed.

Checked steps 1, 2, 4, 9 and 10.

 

If unsuccessful, please check the following, which will help me to narrow down the issue:

*	Open 192.xxx.xxx.xx on the local computer. Does the page load?

Yes, it´s loading the webremote logon page

*	On that page/browser, open a connection to ws://192.xxx.xxx.xx/fsuipc/. Does it work?

No

Result:

Die Website ist nicht erreichbar

Die Webseite unter ws://192.xxx.xxx.xx/fsuipc/ ist eventuell vorübergehend nicht verfügbar oder wurde dauerhaft an eine neue Webadresse verschoben.

ERR_UNKNOWN_URL_SCHEME

 

*	On that page/browser, open a connection to ws://localhost/fsuipc/. Does it work?

No

Same result:

Die Website ist nicht erreichbar

Die Webseite unter ws://localhost/fsuipc/ ist eventuell vorübergehend nicht verfügbar oder wurde dauerhaft an eine neue Webadresse verschoben.

ERR_UNKNOWN_URL_SCHEME

 

But when enter ws://192.xxx.xxx.xx:2048/fsuipc/ on the webremote logon page, it works.

Additionally a screenshot of the configuration of your "Inbound Rule" will help.

Here´s the rule:



Also note, that old versions of iOS do not support WebSocket connections at all. I don't know what iOS your iPad is running, but if it is an older model you should try on a newer machine, perferably another PC or, if you do not have one, your phone maybe.

Both are on newest IOS 17.1.2

**Comment by paulalexandrow** [comment]
Sorry if I was unclear: I meant to try and connect to FSUIPC with the login mask, not just open the ws://…. URLs in the browser.

Also GitHub swallowed your screenshot. You’ll have to reply via the website, not per mail.

Thanks

**Comment by McSchulz** [comment]
Checked steps 1, 2, 4, 9 and 10.

Open 192.xxx.xxx.xx on the local computer. Does the page load?
Yes, it´s loading the webremote logon page on local PC

ws://192.xxx.xxx.xx/fsuipc/ on the webremote logon page does not work
but
ws://192.xxx.xxx.xx:2048/fsuipc/ on the webremote logon page works on the local PC.

Open 192.xxx.xxx.xx on the iPad or iPhone: Yes, it´s loading the webremote logon page
ws://192.xxx.xxx.xx/fsuipc/ or ws://192.xxx.xxx.xx:2048/fsuipc/ on the webremote logon page does not work on iPad and iPhone.

![Screenshot 2023-12-04 174457](https://github.com/paulalexandrow/a32nx-webremote/assets/39158770/16629aaa-bcfb-431c-b8b0-bd67be5f3d60)

Your support is highly appreciate.

Greetings from the snowy north of Hessia.

Mario

**Comment by paulalexandrow** [comment]
Ok, your rule is correct. However, there is something I want to try: Please put `http://192.xxx.xxx.xx:2048/fsuipc/{R:1}` into "URL umschreiben" and let me know if that changes anything.

Also as as temporary solution, I am fairly sure that you could use `ws://192.xxx.xxx.xx:2048/fsuipc/` as WebSocket URL on the iPad **if you open inbound port 2048 in your Defender**. This would result in a setup a little bit different from the intended one, but still safe. (I would then still like to find out what is wrong with the "normal" setup, so I can update the guide if necessary.)

**Comment by McSchulz** [comment]
Changed rule, but sorry, no change.

I add inbound port 2048 in Defender already. I add for iPad and iPhone as well. But for those devices it tells me that an external port it set. 62xxx, yes 5 digits.

**Comment by paulalexandrow** [comment]
> I add inbound port 2048 in Defender already. I add for iPad and iPhone as well. But for those devices it tells me that an external port it set. 62xxx, yes 5 digits.

I do not understand what you are referring to. How do you "add a port for your iPad"? Can you also provide a screenshot of the FSUIPC WebSocket configuration maybe?
