### ISSUE TITLE
Probleme bei der Einrichtung eines Ipads mitt IIS Server

### ISSUE THREAD

**Issue by StefanSch1801** [paulalexandrow/a32nx-webremote#14]
Hallo aus Wien lieber Paul!

Erstmal ein riesiges Dankeschöön für dein feines Tool für den A320FBWNX!

Leider funktioniert bei mir die Einrichtung des Servers für das spiegeln auf andere Geräte nicht! Ich habe alles so gut wie möglich nach deiner Anleitung eingestellt! Jedoch wenn ich nach Punkt 7 die Url http://192.168.0.2 ausprobiere im Internet Explorer bekomme ich immer eine Fehlermeldung! Und zwar die Antwort hat zu lange gedauert!

Kannst du mir vielleicht noch einen Tip geben an was es scheitern könnte?

Es wäre so fein das ganze übers Touchscreen Ipad zu bedienen!

Lg Stefan

**Comment by paulalexandrow** [comment]
Kindly stick with English in this repo, so everybody can profit.

Just to confirm: `192.168.0.2` is just an example URL for the setup guide. You have to use the IP address of _your_ Machine A. Or did you already try that?

**Comment by StefanSch1801** [comment]
Thanks for your answer, i already try it in the evening! It is running!! 😊

MfG
Stefan Schrank

Gesendet von Mail für Windows 10
