### ISSUE TITLE
401 - Unauthorized: Access is denied due to invalid credentiels

### ISSUE THREAD

**Issue by StefanSch1801** [paulalexandrow/a32nx-webremote#17]
Hello Paul, i have a new Problem

when i open my Safari browser , then comes a 401 message, see above!

can you help me?

regards steve

**Comment by paulalexandrow** [comment]
There is nothing to see. Did you forget to add an attachment?

Anyways, I don't think I can help you with this little information. Can you elaborate on the setup you are trying to create and where in the process you are?

**Comment by paulalexandrow** [comment]
no further details provided

**Comment by paulalexandrow** [comment]
no further details provided
