### ISSUE TITLE
Remote connection - socket error

### ISSUE THREAD

**Issue by Louis1505** [paulalexandrow/a32nx-webremote#18]
Hi,

I was following the guide and the youtube video and did everything like written down. I can access the page via the IP Adress, but then I get a error when trying to connect the Web remote (as in the picture). I currently be able to access the site via localhost or external host, but I can not connect. Not on the localhost (except I write "ws://localhost:2046/fsuipc/") or the external host. Hope I can get some help here.

Edit: I use an alternative port because 2048 is not working with FSUIPC, but I used 2046 that is working local

**Comment by Louis1505** [comment]
![image](https://github.com/paulalexandrow/a32nx-webremote/assets/79337777/6f24dbe4-3543-48cf-a9cf-8c53349920aa)

**Comment by paulalexandrow** [comment]
I assume 192.168.178.94 is the external IP of your "Machine A".

- Did you reflect the non-standard port 2046 in your IIS Rewrite Rule?
- Can you connect to ws://192.168.178.94/fsuipc/ when using a browser **on machine A**?
- Can you connect to ws://192.168.178.94:2046/fsuipc/ when using a browser **on machine A**?

**Comment by paulalexandrow** [comment]
no reply - closing.
