### ISSUE TITLE
COM frequencies

### ISSUE THREAD

**Issue by skycamel** [paulalexandrow/a32nx-webremote#19]
Thank you for this very useful add-on!
This is not an issue, rather an enhancement request.
It would be great if you also could include COM1 so we can adjust the frequency.
Reason being is that many users as myself still use older hardware, in my case the VRI MCP v1.
Since now MSFS also uses 8.33 Khz spacing besides the 25 Khz, with the older
hardware it's not possible to input some of the used COM frequency's. This is only a problem with COM and not NAV.
So it would be useful to be able to input a freq with the scratchpad.
Cheers and thanks again
Luc

**Comment by paulalexandrow** [comment]
I will look into it, but I can't make any promises about the feasability.

**Comment by skycamel** [comment]
I don't know if this is useful for you, I'm not a programmer so just pass this on for your info.
https://forum.simflight.com/topic/90465-com-frequency-spacing/?do=findComment&comment=558123

**Comment by paulalexandrow** [comment]
Implemented in 1418423

**Comment by skycamel** [comment]
Hi Paul,I noticed a few days that you updated the webremote and I wanted report back to you sooner but I've been struggling.I installed the new version but with the networked PC I get errors. I also reverted back to the previous version and still get errors. So I'm pretty sure it has nothing to do with webremote but I can't figure it out why.It works 2 out of 10 times when I connect to the webserver and if it works then I can also adjust the VHF radio's, thank you!.I attached some screenshots of the errors I get. Maybe you have some idea why it is happening?Thanks again for making the update!Cheers,Luc

    On Friday, 10 May 2024 at 14:23:21 CEST, Paul Alexandrow ***@***.***> wrote:  
 
 


I will look into it, but I can't make any promises about the feasability.

**Comment by paulalexandrow** [comment]
Github will not add your pictures if you answer by email.

Anyhow, if it works sometimes my best guess would be a changing IP address. Other than that this seems to be a problem with your network and not WebRemote, so I am afraid that I can not give you any further support.
