### ISSUE TITLE
Socket Error: Can't use remote device.

### ISSUE THREAD

**Issue by Reflip** [paulalexandrow/a32nx-webremote#20]
I am unable to connect an external device (in my case a Samsung Tablet) and use it and I am also unable to even control using my localhost (Machine A) to control the plane. I followed all steps with tutorials and the posted correct way and I can't figure it out. I've opened ports on my system, addded a rule, everything correctly and I can't connect still. Please help if possible!

![Capture](https://github.com/paulalexandrow/a32nx-webremote/assets/86016649/556a45ae-d7a7-4bd1-ab13-c1a81b1ac1b3)

**Comment by paulalexandrow** [comment]
If it also does not work locally I would initially rule out the firewall as the problem (still possible though). You want to recheck if both IIS plugins are installed, the `system.webServer/webSocket ` setting is enabled, and the rewrite rule is correctly configured.

Are you on Win 11? My setup is Win 10 and I heard there are minor differences in IIS on Win 11. There is a (French) video on Youtube explaining the differences.

**Comment by Reflip** [comment]
I found the issue with my connection to my external device, kinda solved my own problem 😅

**Comment by aatikturk** [comment]
> I found the issue with my connection to my external device, kinda solved my own problem 😅

having the same issue here. can you please share how did you solve it ? 

Edit:  Nevermind, I've also find my mistake :) forgot to check Websocket protocol when enabling IIS :)
