### ISSUE TITLE
Ipad issue

### ISSUE THREAD

**Issue by mppearce2013** [paulalexandrow/a32nx-webremote#9]
HI, I hope all is well. I have an issue with an older ipad ios 9.5, but with chrome and safari. I can browse to the IIS server and see web remote, but it doesn't seem to have a connect button anywhere.

**Comment by paulalexandrow** [comment]
I will look into it, but to be honest, there is a good chance such old browsers are not supported by some of the libraries WebRemote is using. Could you kindly let me know the exact versions of Chrome and Safari you are using?

**Comment by paulalexandrow** [comment]
As suspected, there is no feasible way to how our version of jQuery can be supported on such an old devices. Sorry.
